### PR TITLE
Update product reservation fields in modal on webshop

### PR DESCRIPTION
**Pull request by ateamcms**
## Developer suggestions
Checkmark if PR:
- [x] *Needs Translations*
- [ ] *Could affect implementations custom css*
- [ ] *Need mobile design help/work*
- [ ] *Design include inconsistent*

## QA checklist
- [ ] Tag @ sashoa if design review needed
- [ ] *No regress in implementations custom css* - changes are not breaking other implementations designes
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- [ ] Translations are done

### CODE REVIEW

**Comment by lexlog** [comment]
@ateamcms @dev-rminds could you please point me where these translations are
Screenshot 2023-10-31 at 10 49 40

Screenshot 2023-10-31 at 10 49 34

**Comment by ateamcms** [comment]
> @ateamcms @dev-rminds could you please point me where these translations are Screenshot 2023-10-31 at 10 49 40
> 
> Screenshot 2023-10-31 at 10 49 34

it is browser validation, native number input

**Comment by lexlog** [comment]
@ateamcms clear, thanks :) then is "needs translation" checkmark actual or something else should be translated?
Screenshot 2023-10-31 at 13 07 37

**Comment by ateamcms** [comment]
@lexlog for example is 'empty' text, I think this is only one translation

image

**Review by lexlog — APPROVED** [review]

**Pull request merged**
