### PR TITLE
product price types and provider edit price type on existing products

### PR DESCRIPTION
**Pull request by dev-rminds**
https://github.com/teamforus/forus/issues/2025
https://github.com/teamforus/forus/issues/2034
https://github.com/teamforus/forus/issues/2012
https://github.com/teamforus/forus/issues/1946

Implementations products/actions list must be checked for visual bugs, some minor css changes where made on general implementation.

### CODE REVIEW

**Comment by maxvisser** [comment]
image
add responsitivity here "Gemeente Groningen betaalt" can easily be on one line; there is enough room :)

**Comment by maxvisser** [comment]
image

if there are no decimals, dont show them.

**Comment by maxvisser** [comment]
image
1. when checking the box; the data on top doesnt change
2. aswell I think user would expect on a fixed discount that it would pay upto the fixed discount when checking the box.

**Comment by dev-rminds** [comment]
https://github.com/teamforus/forus-frontend/pull/1585/commits/a931a88db6c6eb4ed46d2c35024a6ecda00f2e44
Feedback from the PR and following tasks:

https://github.com/teamforus/forus/issues/2042
https://github.com/teamforus/forus/issues/1971

Everything related to product expiration date need to be tested (including mobile apps)

**Pull request merged**
