### PR TITLE
webshop pages add configurations for enabling/disabling some blocks

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Review by dev-rminds — CHANGES_REQUESTED** [review]
I got some errors:

On CMS config edit page:
image

On Webshop:
image

**Review by dev-rminds — APPROVED** [review]

**Comment by lexlog** [comment]
in general - functionality works. 

but found two minor layout bugs
@aghimpu:
1. Left side of providers map page is gone to left ( 3024x964, default 100% zoom)
Screen Shot 2022-10-31 at 7 38 49 PM

2. Empty line on home page when turn off map page
Screen Shot 2022-10-31 at 7 23 00 PM

**Comment by lexlog** [comment]
and two side questions for @sashooa:
1. in figma design there is no free space on page because both of column are used. in reality second column is used only for one block, other space is free. should we keep it like that or change somehow?
Screen Shot 2022-10-31 at 6 56 27 PM
2. now this configuration exists in "configs" page. 
Screen Shot 2022-10-31 at 7 41 24 PM
maybe we should put  this configs to page configuration, while we already have them for all of these pages? to prevent having configuration for same pages in different places
Screen Shot 2022-10-31 at 7 42 13 PM

**Comment by sashooa** [comment]
1. https://www.figma.com/file/2vPDFumPvXyVJFpIYDoAQ7/Configurable-content-on-homepage?node-id=1022%3A80288
2. https://www.figma.com/file/2vPDFumPvXyVJFpIYDoAQ7/Configurable-content-on-homepage?node-id=1022%3A101500
3. ...will be later

**Comment by lexlog** [comment]
@aghimpu in addition to https://github.com/teamforus/forus-frontend/pull/2307#issuecomment-1297447315
there is feedback from Sashoa about space (longer toggle lines and white config button instead of blue)
https://github.com/teamforus/forus-frontend/pull/2307#issuecomment-1298661177 

we will refine these changes on refinement, but if they are already clear for you, provide please ests. for them

option 2 from Sashoa comment is only about making configs button white

**Comment by RobinMeles** [comment]
image

Home settings = Homepagina instellingen
Toggle 1: Show map section (homepage) = Tonen van de map (Homepagina)
Toggle 2: Show products section (homepage) = Tonen van het aanbod (Homepagina)

Provider settings = Aanbieder instellingen
Toggle 1: Show map (providers page) = Tonen van de map (Aanbieder pagina)

Office settings = Vestiging instellingen
Toggle 1: Show map (office page) = Tonen van de map (Aanbieder vestiging pagina)

**Comment by lexlog** [comment]
@RobinMeles there is small difference :) first is provider (one) configs and second is providerS (many) configs
but probably its not very clear naming, can you maybe propose something more concrete instead of that?

and together with that we need to translate "configs" button on dutch and for that same request - imho, it should be something more clear than configs (connected to webshop pages disabling blocks)

**Comment by RobinMeles** [comment]
> @RobinMeles there is small difference :) first is provider (one) configs and second is providerS (many) configs but probably its not very clear naming, can you maybe propose something more concrete instead of that?
> 
> and together with that we need to translate "configs" button on dutch and for that same request - imho, it should be something more clear than configs (connected to webshop pages disabling blocks)

Ah clear, then for second providerS the translation should be aanbiederS instellingen. About the 'configs' button I think it's best to rename it to 'Instellingen'.

**Review by lexlog — APPROVED** [review]

**Pull request merged**
