### PR TITLE
Update validator fund request UI

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Comment by dev-rminds** [comment]
@lexlog depends on this https://github.com/teamforus/forus-backend/pull/1596 to show status label text.

**Comment by GerbenBosschieter** [comment]
@ateamcms since we have merged stuff into the develop we now have some merge conflicts. Since this change will be pretty big for the user and needs some communication, I would like to propose to extend the scope a bit. (BTW I already love it that we switched to table view)

Would be really nice if we could sort/order the fund requests as we currently do with transactions. I know fur sure that validators would like that.

Propose to add sort on:
- ID
- Creation date
- Status

Screenshot 2022-11-29 at 12 03 22
Screenshot 2022-11-29 at 12 03 48

**Review by GerbenBosschieter — DISMISSED** [review]
See comment

**Comment by lexlog** [comment]
additionally to Gerbens comment + other fields

**Comment by ateamcms** [comment]
https://github.com/teamforus/forus-frontend/pull/2387
https://github.com/teamforus/forus-backend/pull/1612

**Comment by lexlog** [comment]
tested main positive and negative scenarios, all works fine. and have minor things to debug/clarify
Screenshot 2023-01-05 at 2 10 38 PM
+ checked sorting from comment above

UI/UX:
- [x] @ateamcms @dev-rminds seems like we need to add "Partner BSN" to "Type" column near BSN value 
( last line in table ) 
Screenshot 2023-01-05 at 1 26 01 PM
call result - added record in record_type_translations for partner bsn id from record_types

- [x] @ateamcms bigger space for eye icon 
Screenshot 2023-01-05 at 1 52 12 PM copy
call result - add answered date into space

- [x] @ateamcms @dev-rminds 
didn't found this in frontend, so don't know is it translation bug with missing whitespace or frontend  
Screenshot 2023-01-05 at 1 59 11 PM
call result - investigated, will change whitespace place in frontend in the frontend

bus/clarifications:
- [x] @GerbenBosschieter @dev-rminds   when adding partner bsn and assigning yourself from application, bsn disappears from application. is it correct ? Valentins answer - yes, should be so
- [x] @dev-rminds @ateamcms just put attention to it to - sorting columns on tables takes 2-2.5sec, probably on prod would take more  - @ateamcms says it looks ok and shouldn't be worse on stage/prod

Translations:
- [x] @GerbenBosschieter @RobinMeles Translator says that here is written that requester CAN apply again, but in reality - can't, should we change it? 
Screenshot 2023-01-05 at 2 16 18 PM

**Review by lexlog — APPROVED** [review]

**Pull request merged**
