### PR TITLE
Vouchers to Tegoeden, Aanbiedingen to aanbod

### PR DESCRIPTION
**Pull request by maxvisser**
Alot of translations are missing still. As these were never added to the translation files. Would maybe be nice to add these aswell to translation file

### CODE REVIEW

**Comment by maxvisser** [comment]
extra checken:
- page titles h1 on webshop
- breadcrumbs on webshop

**Comment by GerbenBosschieter** [comment]
@maxvisser Did you do find and replace all :P? We should run the branch locally and check every text if it still fits in the context of the sentence. So we can prevent stuff like: **We hebben 8 aanbod gevonden**

**Comment by maxvisser** [comment]
I did not change the text as we decided it can be removed. Probably we should do it after merging or on this branch https://github.com/teamforus/general/issues/362

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
I see that some of the words like vouchers is changed to Tegoeden on the dashboard. We can't just do this without any communication with our current clients. Especially considering that the users are already used to this. 

1. The name of the menu item is really important because some pages/functionality looks like each other (voucher, aabiedingsvoucher). So changing this can be really confusing.

2. Who checked if it was changed everywhere. Are the e-mails now also saying tegoeden instead of vouchers? Alignment is really important.

3. What is this sentence?????:  subtitle: "Wanneer iemand een actie doet, die jou betreft op deze website, wordt er een notificatie daarvan hier getoond.",

**Comment by maxvisser** [comment]
discussed this one with gerben; decided to split frontend up into two seperate PR's

**Pull request closed without merging**
