### PR TITLE
vergoedingen webshop update styles

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by aghimpu** [comment]
https://github.com/teamforus/WBR-2023-Webshop-redesign-Nijmegen/issues/2

**Comment by lexlog** [comment]
@aghimpu 
two small things found as a feedback
- footer font (to white)
Screenshot 2023-05-24 at 23 00 29

- separators - there are dots instead of |
Screenshot 2023-05-24 at 23 01 14

**Comment by aghimpu** [comment]
@lexlog I see that in Figma the separators are actually dots, but I'll change it back. I'll fix that text too.

**Comment by lexlog** [comment]
yes, it's correct in terms of aligning result with figma : D
but i guess Sashoa missed the moment when separators changed to "|" , so for consistency of design lets do "|"

**Review by lexlog — APPROVED** [review]

**Pull request merged**
