### PR TITLE
used css from Me page for kindpakket page

### PR DESCRIPTION
**Pull request by maxvisser**
used css from Me page to fix columns in kindpakket page.
added some classes to feature_one and feature_two wrappers; maybe this can be optimized still; I think its better two rewrite css after all css is done though

### CODE REVIEW

**Comment by maxvisser** [comment]
some clutter css can go now still; still need to remove this

**Comment by jamalv** [comment]
Laptop screenshot is too far to the right:

Screenshot 2019-05-17 at 05 39 19

**Comment by maxvisser** [comment]
Is this also on develop?

**Comment by maxvisser** [comment]
If so I will make a new branch for fixing all issues with MacBook.

**Comment by jamalv** [comment]
Yes, also on develop

**Comment by maxvisser** [comment]
done.

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
