### PR TITLE
Fix laptop to component

### PR DESCRIPTION
**Pull request by maxvisser**
moved css from laptop to a laptop specifc component, maybe a start to add some reusable css.

### CODE REVIEW

**Comment by jamalv** [comment]
You can use this image, at the kindpakket page the laptop gets cropped too early:

https://drive.google.com/file/d/1zu06_Uyu4T6rqOQSama_imt5zEbMwv0m/view?usp=sharing

**Comment by maxvisser** [comment]
thanks, will fix this in this pr

**Comment by maxvisser** [comment]
needs testing; @jamalv

**Comment by jamalv** [comment]
I think it's kinda weird that the laptop stretches horizontally. It looks fine, though!

Screenshot 2019-05-21 at 11 54 11

**Review by jamalv — APPROVED** [review]

**Pull request merged**
