### PR TITLE
Change birth date format for product reservation form

### PR DESCRIPTION
**Pull request by ateamcms**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## Developer suggestions
Checkmark if PR:
- [ ] *Needs Translations*
- [ ] *Could affect implementations custom css*
- [ ] *Need mobile design help/work*
- [ ] *Design include inconsistent*

## QA checklist
- [ ] Tag @ sashoa if design review needed
- [ ] *No regress in implementations custom css* - changes are not breaking other implementations designes
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- [ ] Translations are done

### CODE REVIEW

**Comment by lexlog** [comment]
main functio works, but met a case that 3-4-5 digit numbers are accepted and interpreted as d m year
for example 111 is interpreted as 11 jan of 2023

**Comment by ateamcms** [comment]
@lexlog made commit

**Comment by lexlog** [comment]
@ateamcms don't judge me hard : D but had one interesting edge case - you can fill in 01-01-1 ( one number in year )
Screenshot 2023-12-11 at 18 10 29

and it will be accepted by frontend and even by backend 
Screenshot 2023-12-11 at 18 10 37

and another minor problem - validation still says "y-m-d", but should "d-m-y" ( if possible, because i saw that both formats still work )
Screenshot 2023-12-11 at 18 16 15

**Comment by ateamcms** [comment]
@lexlog  added commit, also added pull request to backend https://github.com/teamforus/forus-backend/pull/2045

**Review by lexlog — APPROVED** [review]

**Pull request merged**
