### PR TITLE
Sponsor dashboard, CSV validation upload/download button adjustments

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/forus/issues/1212

### CODE REVIEW

**Comment by maxvisser** [comment]
Hi could also do this on the voucher generator?
image

**Review by maxvisser — CHANGES_REQUESTED** [review]
see comment

**Comment by maxvisser** [comment]
could you fix conflicts?

**Comment by aghimpu** [comment]
> could you fix conflicts?

Yeah, its done now.

**Review by maxvisser — APPROVED** [review]

**Pull request merged**
