### PR TITLE
Release/v0.30.1

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
WCAG Fixes: 
	- Sitemap
	- Alternative texts for user uploaded images
Bank connection feature
add aws rum support

### CODE REVIEW

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Stuff breaks. Something whit live chat. not sure

**Comment by GerbenBosschieter** [comment]
Also: can't acces voucher details via sponsor dahsboard

**Comment by GerbenBosschieter** [comment]
Also: website staging has problems

**Comment by maxvisser** [comment]
> Also: can't acces voucher details via sponsor dahsboard

I will make an issue for this bug

**Review by GerbenBosschieter — APPROVED** [review]

**Review by GerbenBosschieter — APPROVED** [review]

**Review by RobinMeles — APPROVED** [review]

**Pull request merged**
