### PR TITLE
product reservation modal style updates and enhancements

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [x] *Check that dusk tests are working locally on compatible branch*
- [x] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## Developer suggestions
Checkmark if PR:
- [ ] *Needs Translations*
- [ ] *Could affect implementations custom css*
- [ ] *Need mobile design help/work*
- [ ] *Design include inconsistent*

## QA checklist
- [ ] Tag @ sashoa if design review needed
- [ ] *No regress in implementations custom css* - changes are not breaking other implementations designes
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- [ ] Translations are done

### CODE REVIEW

**Review by lexlog — CHANGES_REQUESTED** [review]
- [ ] there is some regress from develop branch on mobile version of reservation modal:
<details>
  <summary>Click me</summary>
Screenshot 2023-08-14 at 13 17 01
Screenshot 2023-08-14 at 13 18 09
Screenshot 2023-08-14 at 13 32 03
Screenshot 2023-08-14 at 13 44 05
Screenshot 2023-08-14 at 13 47 49
</details>

how it looked before
<details>
  <summary>Click me</summary>
Screenshot 2023-08-14 at 14 46 51
</details>

- [ ] plus there is one thing that would be good to fix together with redesign
<details>
  <summary>Click me</summary>
Screenshot 2023-08-14 at 13 06 51
Screenshot 2023-08-14 at 13 06 56
</details>

@aghimpu can you please take a look on this to fix?

**Comment by lexlog** [comment]
@aghimpu i rechecked all from last commit - it fixes issues from the feedback
one thing i'm missing is to how to make translation for these buttons, can you help with this - where are those?
Screenshot 2023-08-15 at 13 09 47

**Comment by aghimpu** [comment]
@lexlog they are in /src/sources/forus-webshop/pug/tpl/modals/modal-product-reserve.pug

**Comment by lexlog** [comment]
@aghimpu thanks!

**Review by lexlog — APPROVED** [review]

**Pull request merged**
