### PR TITLE
Feature implementation dashboard

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/forus/issues/1531

### CODE REVIEW

**Comment by maxvisser** [comment]
image
when more info url is enabled. The 'omschrijving' text area should be disabled (no text input)

uitleg in menu bar should link to the external url aswell. (page is 'disabled')

**Comment by maxvisser** [comment]
image

Could we check if we could align images to the center?
Aswell as add underline and blue color to hyperlinks

**Comment by maxvisser** [comment]
Nice to have: add a button to add URL and image markdown codes like:
```markdown
[Example](https://example.org)

![Example fish](https://flif.info/example-images/fish.png)
```

**Comment by maxvisser** [comment]
I also have a weird interaction bug; where sometimes the text is not visible while there should be text.
https://dev.forus.io/groningen/#!/explanation
image

**Review by maxvisser — CHANGES_REQUESTED** [review]
- [x] Fix 'uitleg' link in menu going to external filled in link if set to active
- [x] move 'more info url'. under textarea
- [x] if explanation link is active, on dashboard cms page the textarea should be hidden
- [x] if explanation link is active and textarea is filled we can hide step-by-step guide and FAQ blocks
- [x] Fix image not being centered
- [x] Fix links not being visible (need underline and blue color)

**Comment by maxvisser** [comment]
the refresh bug is still in; https://dev.forus.io/groningen/#!/explanation when I go to this page and I refresh the text disapears.

**Comment by maxvisser** [comment]
When I go to this page and refresh the text disappears:
https://dev.forus.io/groningen/#!/explanation

**Comment by maxvisser** [comment]
Uitleg menu link should also be shown when logged in (specifically on Groningen currently on dev it does not show) https://dev.groningen.forus.io/

This webshop it does shown but should increase the min-width from 1024 to 1280 or make menu items smaller
image

**Comment by maxvisser** [comment]
nice to have:
image
allow hyperlinks markdown in header tekst

**Comment by maxvisser** [comment]
image
I see some code being added for the hyperlink/image buttons but they are not visible.

**Comment by maxvisser** [comment]
- [x] refreshing the page should still show the text which is entered on the textarea.
- [x] If textarea is empty we should show our old blocks (Step by step guide and FAQ); step by step guide is currently missing.
- [x] show 'uitleg' menu item when logged in (check if minimum width is enough for extra menu item) if not: switch to mobile CSS faster. (maybe instead of 1024 -> 1280px)
- [x] nice to have: buttons to add image and hyperlink markdown
- [x] nice to have: add hyperlink markdown to header subtitle

**Comment by maxvisser** [comment]
image

**Comment by maxvisser** [comment]
image
Buttons are still not visible (I see code which should indicate it should be there?)

**Comment by maxvisser** [comment]
I think removing some margin from the menu is a good fix image

**Review by maxvisser — CHANGES_REQUESTED** [review]
- [x] refresh bug on explanation page webshop still should be fixed
- [x] menu when logged in on Nijmegen implementation

**Review by maxvisser — APPROVED** [review]

**Comment by LindaForus** [comment]
@maxvisser How can we close this? Do you have an update?

**Pull request merged**
