### PR TITLE
Release/v0.28.0

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
WCAG fixes
Product reservations
tooltip product creation (explaining price types: for ex. discounts / free )
cms banner removal
Ordering Physical card confirmation screen
Sponsor dashboard, add product delete
Notification modal, adjust layout teamforus/forus#2283
Webshop header increase margin bottom teamforus/forus#2319

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
- Connecting physical card to voucher doesn work. Results in 500 error

Screenshot 2021-07-08 at 13 44 55

**Comment by GerbenBosschieter** [comment]
Cant open a voucher that is connected to digital account.

**Account:** 
Screenshot 2021-07-08 at 13 48 55

**Error**
Screenshot 2021-07-08 at 13 53 17

**Comment by GerbenBosschieter** [comment]
So far I haven't had any succesfull upload for bulk. Get error messages, error 500. Or that user limit is reached while its not correct. Screen stuks at loading.

Don't even know where to start at this moment. Would like to see an example where it does work

**Comment by GerbenBosschieter** [comment]
Missing translation

Screenshot 2021-07-09 at 10 12 10

**Comment by GerbenBosschieter** [comment]
Missing translation

Screenshot 2021-07-09 at 10 15 42

**Comment by GerbenBosschieter** [comment]
Missing expiration date

Screenshot 2021-07-09 at 10 24 39

**Comment by GerbenBosschieter** [comment]
This issue is really annoying and would like to see it fixed in this PR:
https://github.com/teamforus/forus/issues/2325

**Comment by GerbenBosschieter** [comment]
Missing images. My assumption is that this is only occurring on staging and has something to do with S3 buckets. But I would like to have an representation of the production environment during acceptence testing, so I dont have to assume things. 

If this doens't occur on production its fine, but we should still fix it on staging

Screenshot 2021-07-09 at 10 30 10
Screenshot 2021-07-09 at 10 30 23
Screenshot 2021-07-09 at 10 30 13

**Comment by GerbenBosschieter** [comment]
CSV bulk upload for reservations doesn't work properly. The error tells me a user limit is reached for 2 cards for a specific product. I expect that reservations will be added to the list for the other ones that don't give an error. This doesn't happen. In this test I have only used card numbers that are not assigned to an account.

Screenshot 2021-07-09 at 11 05 11


**CSV I used**
Screenshot 2021-07-09 at 11 02 54

**Comment by GerbenBosschieter** [comment]
@maxvisser missing some transaltions

Screenshot 2021-07-09 at 13 25 18

**Comment by GerbenBosschieter** [comment]
Another missing translation

Screenshot 2021-07-09 at 13 30 04

**Comment by GerbenBosschieter** [comment]
@maxvisser another one

Screenshot 2021-07-09 at 13 59 23

**Comment by GerbenBosschieter** [comment]
Server error by creating single reservation This happends when I enter note. If leave the note empty it's will be added to the list

Screenshot 2021-07-09 at 14 02 21

**Comment by GerbenBosschieter** [comment]
Error message when uploading CSV file should be changed:

**Current**
Screenshot 2021-07-12 at 09 54 09


**Change to:**
Screenshot 2021-07-12 at 11 14 45

Text figma:
https://www.figma.com/file/tDbMnCbcvU0aiwxmmWvYld/Directly-pay%3A-Provider-by-using-plastic-card?node-id=667%3A2875

**Current**
Screenshot 2021-07-12 at 11 17 57

**Change to:**
Foutmelding: Kan geen reserveringen aanmaken voor 1 rij(en)

**Comment by GerbenBosschieter** [comment]
Bug with rquester signup flow (stadjerspas - Groningen). Results in Error 500, the request itself gets send as an validation request

Screenshot 2021-07-12 at 16 36 50

**Comment by GerbenBosschieter** [comment]
Same problem with Meedoenregeling. No request possible

Screenshot 2021-07-13 at 09 02 35

**Comment by GerbenBosschieter** [comment]
From this release on we will show the multiplier on the voucher page. Most of the time this information will be correct. If muncipality makes use of prevalidations and activations it will not.

Noordoostpolder it's multiplier is based on the record of amount of adults and children. In the example below you can see that the activation code is created for 1 adult and 1 kid. After activation the voucher page displays: 1 persion (multiplier). Although this logical technically, it could be really confusing for the muncipality of Noordoostpolder.

Screenshot 2021-07-13 at 09 08 57


Screenshot 2021-07-13 at 09 08 19

**Comment by maxvisser** [comment]
image

**Comment by maxvisser** [comment]
image

**Comment by maxvisser** [comment]
image

**Comment by maxvisser** [comment]
Editing product as a sponsor gives error 500
```
dev.ERROR: Return value of App\Notifications\Organizations\BaseOrganizationNotification::getPermissions() must be of the type array, string returned 
{
    "userId": "0xa92eb3e163b15290d3b640ef88102807c26b2a82",
    "exception": "[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Notifications\\Organizations\\BaseOrganizationNotification::getPermissions() must be of the type array, string returned at /var/app/current/app/Notifications/Organizations/BaseOrganizationNotification.php:39)\n[stacktrace]\n#0 /var/app/current/app/Notifications/Organizations/BaseOrganizationNotification.php(52): App\\Notifications\\Organizations\\BaseOrganizationNotification::getPermissions()\n#1 /var/app/current/app/Notifications/BaseNotification.php(92): App\\Notifications\\Organizations\\BaseOrganizationNotification::eligibleIdentities(Object(App\\Models\\Fund))\n#2 /var/app/current/app/Models/Product.php(596): App\\Notifications\\BaseNotification::send(Object(App\\Services\\EventLogService\\Models\\EventLog))\n#3 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): App\\Models\\Product->App\\Models\\{closure}(Object(App\\Models\\Fund), 0)\n#4 /var/app/current/app/Models/Product.php(598): Illuminate\\Support\\Collection->each(Object(Closure))\n#5 /var/app/current/app/Models/Product.php(680): App\\Models\\Product->resetSubsidyApprovals()\n#6 /var/app/current/app/Http/Controllers/Api/Platform/Organizations/Sponsor/Providers/ProductsController.php(119): App\\Models\\Product->updateFromRequest(Object(App\\Http\\Requests\\Api\\Platform\\Organizations\\Sponsor\\Providers\\Products\\UpdateProductsRequest))\n#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\Platform\\Organizations\\Sponsor\\Providers\\ProductsController->update(Object(App\\Http\\Requests\\Api\\Platform\\Organizations\\Sponsor\\Providers\\Products\\UpdateProductsRequest), Object(App\\Models\\Organization), Object(App\\Models\\Organization), Object(App\\Models\\Product))\n#8 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)\n#9 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\Platform\\Organizations\\Sponsor\\Providers\\ProductsController), 'update')\n#10 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()\n#11 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()\n#12 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))\n#13 /var/app/current/app/Http/Middleware/ApiAuthMiddleware.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ApiAuthMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#15 /var/app/current/app/Services/Forus/Session/Middleware/ForusSessionMiddleware.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#16 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Services\\Forus\\Session\\Middleware\\ForusSessionMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#17 /var/app/current/app/Http/Middleware/ClientTypeMiddleware.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#18 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ClientTypeMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#19 /var/app/current/app/Http/Middleware/ImplementationKeyMiddleware.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#20 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\ImplementationKeyMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#21 /var/app/current/app/Http/Middleware/LocaleMiddleware.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#22 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\LocaleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#23 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#24 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#25 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#26 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#27 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))\n#28 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))\n#29 /var/app/current/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))\n#30 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))\n#31 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))\n#32 /var/app/current/app/Http/Middleware/RecordApmTransactions.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#33 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\RecordApmTransactions->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#34 /var/app/current/vendor/fruitcake/laravel-cors/src/HandleCors.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#35 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#36 /var/app/current/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#37 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#38 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#39 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#40 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#41 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#42 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#43 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#44 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#45 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#46 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#47 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))\n#48 /var/app/current/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))\n#49 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#50 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))\n#51 /var/app/current/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#52 {main}\n"
}
```

**Comment by maxvisser** [comment]
when provider cancels reservation euro's don't seem to come back on voucher
image

**Pull request merged**
