### PR TITLE
Sign up flows

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Review by maxvisser — CHANGES_REQUESTED** [review]
## Provider signupflow feedback

###  Install Me-app and creating with email adress are change around
image

Provider has Me-app step first (as they need  to install the me-app)
Sponsor, validator and requester don't

So on sponsor and validator signupflows all is well but only on provider signupflow the step of creating an identity should have Me app first instead of creating identity by email

### IBAN placeholder text
image
Example should be 'Voorbeeld:"
also placeholder should be both fields

### Remove 1 optional 

image
Two times optional;
Dutch word for optional is "Optioneel"

How it should be:
image


### Text fix Localization: Adres
image
Address should be Adres


### Text fix Localization: From/till
image
From -> Van
Till -> Tot


### Text fix: wrong description
image
should be:
De afbeelding dient vierkant te zijn met een afmeting van bijvoorbeeld 400x400px.
Toegestaande  formaten: 
JPG, PNG 


### No error/warning when pressing submit with uncompleted opening times
image
1. would be nice to somehow now what to fill in (if we could show :00 already);
2. after pressing submit I got no error telling me I did not add :00; no error at all


### Google maps does not get coordinates from my address
image
After submiting my office my address land somewhere in the sea near africa


### Add office step: Cancel button is broken
image
Pressing cancel after adding another office results in a error on a field instead of closing the add office state. Cancel is basically useless


### Texts are missing
image
texts are missing (need figma prototype?)

Title: Medewerker uitnodigen

Description:
U staat op het punt om een medewerker uit te nodigen voor uw organisatie. Er wordt een uitnodigingsmail verstuurd naar [info@example.org]. De medewerker kan de link in de mail gebruiken om in te loggen het dashboard. 

Submit: Versturen 
Cancel: Annuleren

### Texts are missing
image
texts are missing

### No test transaction (maybe intended) step should be different if so
image
there was no test transaction (no QR to scan) while this step does describe me I will be doing a test transaction.


### Employee mail link does not work
image
https://dev.api.forus.io/api/v1/identity/proxy/confirmation/redirect/1d52c3d2205829a2325a9ff1338b6d9143f59bd7725ed5361a489f9487aad4b983d9b4a9a5c352d5f39801b21052cfb724abefd4cdc1a228c6e1bc5a8bffddcded79c21f7697ebd90e0d00d1e91e996ce729a9db5b3127481a64830f8824242b0878af2f/provider/general

I added myself as an employe; I clicked the link in the email but I got to a 404 page.

## Sponsor feedback

image

- [ ] remove vorige stap

- [ ] add padding to button 

- [ ] adjust styles of button:
image

## Validator feedback

### Welcome text fix
image
text should be about validator instead of provider (bold text changed):
Via dit online formulier kunt u uw organisatie aanmelden als **validator**. De volledige aanmeldprocedure duurt ongeveer 5 minuten.

### choose organization fixes
image
- carret is behind vorige stap instead of before

image
- Image has no rounded corners

**Comment by maxvisser** [comment]
Provider feedback
- [ ] Install Me-app and creating with email adress are change around
- [ ] IBAN placeholder text
- [ ] Remove 1 optional
- [ ] Text fix Localization: Adres
- [ ] Text fix Localization: From/till
- [ ] Text fix: wrong description
- [ ] No error/warning when pressing submit with uncompleted opening times
- [ ] Google maps does not get coordinates from my address
- [ ] Add office step: Cancel button is broken
- [ ] Texts are missing
- [ ] No test transaction (maybe intended) step should be different if so
- [ ] Employee mail link does not work

# Sponsor feedback
- [ ] remove vorige stap on signup success
- [ ] add padding on button
- [ ] change style of button

# Validator feedback
- [ ] adjust welcome text (one word)
- [ ] Vorige stap on choose organization has carret after instead of before
- [ ] image has no rounded corners of choose organization

**Review by maxvisser — CHANGES_REQUESTED** [review]
:duck:

**Review by maxvisser — CHANGES_REQUESTED** [review]
### Provider feedback
- [ ] Install Me-app and creating with email adress are change around (only for provider; all other signupflows are okay)
- [ ] IBAN placeholder text
- [ ] Remove 1 optional
- [ ] Text fix Localization: Adres
- [ ] Text fix Localization: From/till
- [ ] Text fix: wrong description
- [ ] No error/warning when pressing submit with uncompleted opening times
- [ ] Google maps does not get coordinates from my address
- [ ] Add office step: Cancel button is broken
- [ ] Texts are missing
- [ ] No test transaction (maybe intended) step should be different if so
- [ ] Employee mail link does not work

### Sponsor feedback
- [ ] remove vorige stap on signup success
- [ ] add padding on button
- [ ] change style of button

### Validator feedback
- [ ] adjust welcome text (one word)
- [ ] Vorige stap on choose organization has carret after instead of before
- [ ] image has no rounded corners of choose organization

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-frontend/pull/1046/commits/a1085f44e72ba50f5f4b94c442db5f9174a7bbe5 solves this one
https://github.com/teamforus/forus/issues/1007

**Comment by aghimpu** [comment]
https://github.com/teamforus/forus-backend/pull/677 fixes the confirmation link for email sent to employee.

**Comment by maxvisser** [comment]
fix conflicts; check if registration needs fixing

**Review by maxvisser — APPROVED** [review]

**Pull request merged**
