### PR TITLE
Update signup flow texts and minor fixes

### PR DESCRIPTION
**Pull request by jamalv**
## Step 1:
related to https://github.com/teamforus/forus/issues/376 and https://github.com/teamforus/forus/issues/361

## Step 2: 
- [ ] still need to do the tooltip

### CODE REVIEW

**Comment by jamalv** [comment]
Regarding step 1:

@maxvisser I am not sure about adding the two download buttons, as we want the user to open the link on their mobile device and not on their desktop this might be confusing. I'd prefer something like: https://github.com/teamforus/forus/issues/361#issuecomment-438978527 especially now that the android link will go directly to an APK file. On desktop that will not be good.

And of course a textfield for your mobile phone number as discussed in: https://github.com/teamforus/forus/issues/361 😎

**Comment by jamalv** [comment]
## Step 3: 
Needs categories for "diensten en activiteiten and for monday, it should also be the default.

## Should be:
_please ignore the red lines_
screenshot 2018-11-18 at 16 05 54

## currently:
screenshot 2018-11-18 at 16 07 18

**Comment by jamalv** [comment]
## Step 4:
- When reloading I get redirected to the dashboard, organisation overview.
- People will probably accidentally add another office, there should be an X on the top right to delete it.

**Comment by jamalv** [comment]
Apply funds on step 7 did not show, might be because there are no funds on dev.

**Comment by maxvisser** [comment]
There are no funds on dev

**Comment by maxvisser** [comment]
I added only cultuur as category to the database to test how it works

**Review by maxvisser — APPROVED** [review]
Ziet er goed uit!

**Pull request merged**
