### PR TITLE
Fund faq and fund sign-up button

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/EFO-2021-external-funds-overview-Nijmegen/issues/18
https://github.com/teamforus/EFO-2021-external-funds-overview-Nijmegen/issues/24

### CODE REVIEW

**Comment by maxvisser** [comment]
@aghimpu  could you fix conflicts;
and I could not get the creation of a FAQ item to work. (it gives me an console error); could be because of the merge conflicts i tried to solve myself during sprint demo prep.

**Comment by maxvisser** [comment]
> regarding the FAQ and how it looks on the webshop, I'm not really sure how it should look. Right now we have this
> image
> 
> if I make it take the full width it seems rather ugly
> image
> or do I just keep the width and only left align it? would be nice to know what you think

I feel that we have this problem with all the default block as well
(see the block of no results above)

> ok, then I just make it to take the full width to be consistent at least

Yes I think we should maybe make all content 930px width (atleast CMS pages)
with margin auto (center the block on the page)
for styling I also have add some styling in the issue
image
site which I took this screenshot from: https://www.nijmegen.nl/diensten/uitkering-schulden-laag-inkomen/meedoenregeling/

I tried recreating this styling (in the issue https://github.com/teamforus/EFO-2021-external-funds-overview-Nijmegen/issues/16#issuecomment-952879477)
Maybe we can add this styling for implementation Nijmegen
As this is how these blocks look on their site

Also I believe we should make this user editable or remove it
image

@dev-rminds what do you think about making the width of the pages smaller?
image

I would propose to:
- Make the max-width of pages smaller (maybe 930 px?); atleast for the fund details page / cms pages
- Allow sponsor to change title
- Implementing custom styles for Nijmegen implementation (so they look similar to their website)

**Comment by maxvisser** [comment]
Lets not make the FAQ title mandatory

**Comment by dev-rminds** [comment]
included in https://github.com/teamforus/forus-frontend/pull/1987

**Pull request closed without merging**
