### PR TITLE
Develop.new providers and products pages

### PR DESCRIPTION
**Pull request by dev-rminds**

### CODE REVIEW

**Comment by maxvisser** [comment]
needs to be mobile ready first before getting merged. for context why: 67% of all requests last month came from smartphones/tablet (webshop)

mobile design are in shared google drive.

**Comment by maxvisser** [comment]
- [ ] openingstimes should have a no openingstimes available contact provider for openingstimes message dutch: 'Aanbieder heeft geen openingstijden ingesteld. Contacteer aanbieder voor de openingstijden.'
image

- show only business types which are connected to implementation
   - also clear dropdown when user clicks on it
image

**Comment by maxvisser** [comment]
list products are not clickable 
image

**Comment by maxvisser** [comment]
I would zoom lock map on office details page (user needs to hold ctrl to zoom) i think its gestureHandling: cooperative; This should only be the case on the details page (that map only)

I removed the business type dropdown from provider list as it is not usefull without filtering out the business types that are not on webshop

**Comment by maxvisser** [comment]
on the provider map on mobile; the footer is really annoying. I would not mind hiding the footer on this page. I just added z-index: 2 to the css to have the map above footer; probably not the best solution

**Comment by maxvisser** [comment]
On mobile map needs two fingers to move around; I would prefer to just be able to do it with one finger directly.

**Comment by jamalv** [comment]
Please fix scrolling behaviour on the map; when scrolling the footer moves over the map. Also, initially it hides some controls (zoom in and out)

Desired behaviour:
- [ ] Footer is stuck to the bottom of the page and doesn't scroll independantly
- [ ] Full page can be scrolled (cursor needs to be on something else then the map)

**Comment by jamalv** [comment]
@maxvisser, ah, just saw your comment as well :)

**Comment by maxvisser** [comment]
Video of me using map on mobile:
https://photos.app.goo.gl/KnyyWtMHJG7ZfDdo7

seems that the overlay of offices disables moving the map (you can't use any controls after clicking on a pin; refresh makes make map work for abit but after a few seconds its get locked again)

**Comment by maxvisser** [comment]
Screenshot_20191230_090029_com kiwibrowser browser

small issue with organization image being too tall on mobile

**Comment by maxvisser** [comment]
Small point of feedback:
image
I would not make the whole card go to organization details; I think we should only make the name and image refer to organization details page. When user clicks on anything else we should toggle the list.

**Comment by dev-rminds** [comment]
> Video of me using map on mobile:
> https://photos.app.goo.gl/KnyyWtMHJG7ZfDdo7
> 
> seems that the overlay of offices disables moving the map (you can't use any controls after clicking on a pin; refresh makes make map work for abit but after a few seconds its get locked again)


Couldn't reproduce the issue

Checked on:
- Android - Chrome
- IOS - Chrome
- IOS - Safar

https://drive.google.com/drive/folders/1-7-ovZ1sXiHmcy__bSV9E3h9inHlwlXZ?usp=sharing

**Review by maxvisser — APPROVED** [review]

**Pull request merged**
