### PR TITLE
improvements for the mobile version of webshop

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
Even though this PR is still in draft and not my time to check it out yet, I did since I am really curious. I already have some feedback I would like to see processed. 

- [x] The login button should be on the top right and "start aanvraag" on the left. Now it's switched around
- [x] If there are two buttons, it would be nice to make sure that there are the same width (only on mobile) to it's look more centered and aligned with the rest
Screenshot 2023-04-17 at 09 53 31

- [x] The search feature itself is not as desired. 
    - The search input is being displayed if you tap on search button. But it's not hidden if you click on it again, it's stays visible. 
    - The search input is being displayed if you tap on the search button, but instead over overlaying the top navbar it still appears below. 
    - The icon of the search button doesn't change after you open the search input. It should change to a cross. 
    - If search results are openend you can scroll horizontally if the device is to small to display it next to each other. This is the desired behaviour but some minor detail should change.  If you would scroll horizontally the whole `search-result-content` is scrolling horizontally. It would be more desired if only the `search-result-sidebar` would scroll and the content itself won't

Screenshot 2023-04-17 at 09 59 00

**Comment by lexlog** [comment]
waits gerbens second review
https://github.com/teamforus/DevOps/issues/177#issuecomment-1529488749

**Comment by GerbenBosschieter** [comment]
**Search**
- [x] When "tapping" on search the search bar does overlay as desired. But without putting anything into the search you cant cancel it. Please make sure user can cancel their search wihout entering something. So always show the "cross" to cancel.

Screenshot 2023-05-04 at 09 26 22

Screenshot 2023-05-04 at 09 27 55

**Comment by GerbenBosschieter** [comment]
**Search design**

It's a small thing but in Figma we have made slightly different design choices in Figma then we have in this branch

- [x] Background color should be #FBFBFB 
- [x] Border color of the search input is now black, should be #DBDCDB
- [x] Inlog button is missing an icon 

Screenshot 2023-05-04 at 11 01 56

- [x] The buttons have a margin right. Therefor it's not completely aligned and centered. Removing margin-right will result in other design problems. Goals is to have the samen amount of space between button and left/right icon. Or have the left button exaclty positioned as the right button so it's alligned with the top left icon
Screenshot 2023-05-04 at 11 03 56

- [x] Border color of this button should change to general blue color (#305dfb). Please take in consideration that this color could be differect per implementation and we are using the correct variable.

- [x] If sticky footer is openend we would like to have a full page just as the figma design has

**This branch**
Screenshot 2023-05-04 at 11 22 57

**Figma**

Screenshot 2023-05-04 at 11 25 10

**Comment by GerbenBosschieter** [comment]
- [x] Please switch buttons (just like logging in). "logout" button on the right and "start aanvraag" on left.
- [x] Please add icon to logout, we use mdi for that `em class="mdi mdi-logout"`

Screenshot 2023-05-04 at 16 59 09

**Comment by GerbenBosschieter** [comment]
Started reviewing again. Looks like most feedback is processed. I am now analysing the impact on all other implementations. I do see some weird visual stuff over there, but not sure if thats due the scss variables or thing branch. 

Only briefly checked it. To really do good analysis per implementation I need some time

**Comment by GerbenBosschieter** [comment]
Refinement update: will finish review and aligning implementations (translations) this sprint

**Comment by lexlog** [comment]
sprint status:
- @GerbenBosschieter Alex fixes are done
- @GerbenBosschieter want to fix translations and rechecked thing he found above, then assign Valentin

friday 12 status - @GerbenBosschieter planning to do it today / start of next week

**Comment by lexlog** [comment]
sprint status - @GerbenBosschieter found some smaller things, scheduled 3h for alex, still planning to have this during start of this week

**Comment by GerbenBosschieter** [comment]
@aghimpu So there is one situation that we didn't cover.

In `qdt-env.js` we have a frontend flag thats called:  `genericSearch` and can be set to _true_ or _false_. If it's set to false, there is no generic search. So maybe it is not the most eye catching solution but for now I would just say: if `genericSearch` is false, hide search option on mobile and obviously desktop but thats already the case. To prevent this:

Screenshot 2023-05-15 at 16 13 24


Example:

```js
core.editPlatform('webshop_general', (platform) => {
        platform.setEnvData({
            api_url: apiUrl,
            client_key: baseImplementationKey,
            client_type: 'webshop',
            sessions: sessions,
            google_maps_api_key: google_maps_api_key,
            matomo_site_id: false,
            flags: {
                showStartButton: true,
                showStartButtonText: 'Start aanvraag',
                startPage: {
                    combineColumns: true
                },

                //menu settings
                fundsMenu: true,
                fundsMenuIfLoggedOut: true,
                meAppMenu: false,
                forusPlatformMenu: false,
                portfolioMenu: false,
                aboutSiteMenu: false,
                genericSearch: false,
            },
        });

        platform.setDestRootPath(outputRoot + '/general');

        platform.editTask('js', (task) => {
            task.minify = minify;
            task.sourcemap = sourcemap;
            return task;
        });

        return platform;
    });
```

**Comment by GerbenBosschieter** [comment]
@aghimpu 

We also have something else whats more a **should have** then a **must have**. Because it will probably only occur if you are using the webshop as a tester.

Would be nice to prevent this behaviour. Please look at [this](https://drive.google.com/file/d/1C-upoQqSGC0FbTPidCuMdTmj14mVuRQj/view?usp=share_link) video to understand.

**Comment by GerbenBosschieter** [comment]
Briefly checked. @aghimpu processed al feedback. 

- [x] Check how these changes impact all implementations and fix translations/smaal frontend stuff if needed

**Comment by GerbenBosschieter** [comment]
@aghimpu found another one (this will be the last one haha)

The implementation: `vergoedingen` is the only implementation where we don't have the two buttons, so:
In `qdt-env.js` we configured `vergoedingen` with:

```js
flags:
    showStartButton: false;
```

But on mobile it's still displayed.  Please make sure if that flag is set to false that "start" the following things will happen on mobile:
- [ ] Hide the "Start" button
- [ ] Add more width to "Inloggen" (see image below)

Screenshot 2023-05-19 at 17 13 00

**Comment by lexlog** [comment]
status - fix will be planned next sprint with low prio

**Comment by lexlog** [comment]
status - @aghimpu will start this after finish 2 left sprint issues before starting categories fix

**Comment by lexlog** [comment]
devops note - Gerben will check out PR tomorrow to provide additional feedback to Alex

**Comment by lexlog** [comment]
refinement meet - lower prio for Gerben than in_use Nijmegen issues, will be done after that
next sync - sprint plan

**Comment by GerbenBosschieter** [comment]
@aghimpu Reviewed it again and I think it's all good but not 100% sure. For vergoedingen I can't really make a good judgment since this pull request doesn't have the style changes (white color) as on other branches. And the old one has the "problem" of the image below

Screenshot 2023-06-23 at 10 11 53

Since this PR has some merge conflicts I don't want to touch myself so I can;t check it out myself.

@aghimpu Could you fix the merge conflicts and merge develop branches into this one so I can check vergoedingen webshop for the last time :)

Rest is al good to go

**Comment by GerbenBosschieter** [comment]
@aghimpu I made some commits for vergoedingen webshop so the screenshot below will not happen. But since we did some changes on css, variables and whatever more I am not sure if my part needs to be refactored or not. Could you (or @dev-rminds ) could check it out. For the rest it's now 100% done  See [commit](https://github.com/teamforus/forus-frontend/pull/2634/commits/22c7c8af5685655daf70070d8c9ff1b46b4db006)

Screenshot 2023-06-26 at 15 29 07

**Comment by dev-rminds** [comment]
@aghimpu could you please check for any potential regressions?

**Comment by lexlog** [comment]
refinement note for @aghimpu - check how it will work regarding to the [wcag issue](https://app.zenhub.com/workspaces/sprint-5f61c6c0a53fb84e755c82f6/issues/gh/teamforus/wcag-audit-2023/22#issuecomment-1621641977)

**Comment by aghimpu** [comment]
I checked the wcag issue and it solves it as well

**Comment by lexlog** [comment]
- [x] menu intersect
Screenshot 2023-07-11 at 22 48 19

- [x] search icon is not accessible by keyboard (wcag)

**Review by lexlog — APPROVED** [review]

**Pull request merged**
