### PR TITLE
fund description_short increase limit to 500

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by lexlog** [comment]
@dev-rminds @aghimpu 
Was it planned to show "show more" button even for fund with small description? I think we shouldn't
Screenshot 2023-01-25 at 6 37 54 PM

**Comment by dev-rminds** [comment]
> @dev-rminds @aghimpu Was it planned to show "show more" button even for fund with small description? I think we shouldn't Screenshot 2023-01-25 at 6 37 54 PM

fixed

**Review by lexlog — CHANGES_REQUESTED** [review]
there is feedback from design review
https://github.com/teamforus/DevOps/issues/203#issuecomment-1404940161
(since PR is not urgent, we can do it with the same PR)

**Comment by lexlog** [comment]
@dev-rminds @aghimpu I see update commits, so we can assign QA and review or still development planned?

**Review by lexlog — APPROVED** [review]

**Pull request merged**
