### PR TITLE
Release/v0.21.0

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
added texts for CMS jij/u
Voucher generator: Modal voucher create, show required fields
Webshop: sample products, use a different endpoint
Webshop: changed Me-app images, changed to dutch dl buttons
sponsor actions: expiration date
Fixed texts: action to subsidy
Sponsor: Approve multiple funds
Sponsor add products
Sponsor add products: dropdown menu on provider products table
textual fixes

### CODE REVIEW

**Comment by maxvisser** [comment]
image
montserrat font-family is not loading in.

**Comment by GerbenBosschieter** [comment]
Missing translation when start activation flow on https://winterswijk.staging.forus.io/. 

Screenshot 2021-03-11 at 10 40 19

**Comment by GerbenBosschieter** [comment]
"Verder gaan Me-app" = robotic language. Looks like a sentence to avoid using Je/U, thats okay but robot style is not okay. Should change text to: "Aanmelden me de Me-app" or "Verder gaan met de Me-app"

Screenshot 2021-03-11 at 10 44 31

**Comment by GerbenBosschieter** [comment]
Missing translation on product voucher

Screenshot 2021-03-11 at 11 39 16

**Comment by GerbenBosschieter** [comment]
Change: "Niet uw beheer" to "In beheer van de sponsor"

Screenshot 2021-03-11 at 14 27 38

**Comment by GerbenBosschieter** [comment]
Position "Opties" above "Bekijk aanbod" . This doesn't happen on the provider tab but it does happend when you click on product of provider

Screenshot 2021-03-11 at 14 31 39

**Comment by GerbenBosschieter** [comment]
Sever error when I try to invite providers from other fund

Screenshot 2021-03-11 at 16 59 14

**Comment by maxvisser** [comment]
Not being able the invite providers is also an issue on production. Yesterday I created an issue in Forus to fix it.

**Comment by GerbenBosschieter** [comment]
Problem with application form for Nijmegen Meedoen and Busvoordeel. If someone (BSN) already is added to the voucher generator And tries to login with Digid , he will receive error: fund already received.  

Screenshot 2021-03-12 at 09 35 17

**Comment by GerbenBosschieter** [comment]
So there are some things in the new feature that should be solved . But the feature itself does work. So releasing it is important. The following things are needed and should be solved ASAP. There are also som UX things but we should work this in Figma.

**ASAP:**
- Images is not added with the copy
- Category is not added with the copy
- As a sponsor I would expect that the “old” product/action will be stopped after starting an action on the copy. This doesn’t happen
- As a sponsor you shouldn’t be apple to copy a product that you already manage
- As a sponsor you should be able to click on edit if you opened the product

**Comment by maxvisser** [comment]
1. Copying images is a bit more complex as the other data is only prefilled, like downloading and prefilling the image is not an option.
2. categories is a bug (should work); if you just press submit after copying it does set the category its just not visible on the edit screen.
3. copying means copying the data without touching the old so its weird to stop without user interaction the old subsidy
4. Copying a product which was creating as a sponsor is a nice thing if you want to create a new product but use an old product as a baseline/template
5. the edit button is something we will add

**Pull request merged**
