### PR TITLE
Sponsor dashboard, add toggle to accept both budget and products on p…

### PR DESCRIPTION
**Pull request by aghimpu**
…roviders page
https://github.com/teamforus/forus/issues/1336

### CODE REVIEW

**Comment by maxvisser** [comment]
I think you misunderstood the issue. It was about when a user toggles allow_budget it would also toggle allow_products automatically.

A extra toggle is abit overkill

**Comment by danrminds** [comment]
We discussed it with Jamal, and came up to this. Neither me or Valentin like the idea of toggling something you did not press to toggle

**Comment by maxvisser** [comment]
I think the three toggles is abit weird on list. Maybe add the approve all on list and the approve budget and approve products on details? 

Will discuss this with Jamal when hes available

**Comment by danrminds** [comment]
It actually was meant to be not a toggle (the third one) but a button that would disappear  if both are toggled

**Comment by jamalv** [comment]
Yes, as mentioned we discussed adding a button that has the same behaviour as before (so turning both toggles on)

**Pull request closed without merging**
