### PR TITLE
make the fund description position configurable on the fund details page

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Comment by lexlog** [comment]
if there are F.A.Q. questions set then products block is splitting description and f.a.q in two parts 
Screenshot 2023-07-12 at 10 42 57

proposal:
- [ ] put f.a.q before products
- [ ] move f.a.q. configuration in fund edit details dashboard before "position of the content"
Screenshot 2023-07-12 at 13 13 31


-----
- [ ] @lexlog create separate issue for fund descriptions content ( communication page)

**Review by lexlog — CHANGES_REQUESTED** [review]
check comment

**Comment by aghimpu** [comment]
@lexlog should we also override the f.a.q block too on the webshop if the "override" option for the fund description is set (the same way we do with the products block)?

**Comment by lexlog** [comment]
status - waiting answer from Linda to question from Alex

**Comment by LindaForus** [comment]
@lexlog @aghimpu 
The best situation for the users would be if they are able to set these content blocks separately from each other. 
So that they can set this visibility (on/off) of the content block in the sponsor dashboard for:
- Text description
- Products
- FAQ

Is this possible? If not - please keep the FAQ.

**Comment by lexlog** [comment]
@aghimpu can you check comment above?

**Comment by aghimpu** [comment]
@linda it's not really possible to do this in a clean way, allowing to set up both the visibility and each element order unless we rewrite our CMS or so. I'll just keep FAQ.

**Comment by lexlog** [comment]
discussed on refinement - for now @aghimpu will just place f.a.q before product ( hardcoded )

**Comment by lexlog** [comment]
something unclear now appear in dropdown of content that could lead to confusion of users

1) position of content is mixed up with products and f.a.q, we need to rediscuss is it possible to configure it separately
2) without enhancement above, with override option we should set description before f.a.q.
3) description configuration should be nearby block description in fund edit 



how it currently works:
- override
  - product are disappeared 
  - description is after F.A.Q.
- before default content
  - description is before product and F.A.Q. 
- after default content
  - description is after F.A.Q. and products

**Comment by lexlog** [comment]
notes:
- position is position of content. content is always description + f.a.q., always in this order

**Review by lexlog — APPROVED** [review]

**Pull request merged**
