### PR TITLE
Provider signup flow

### PR DESCRIPTION
**Pull request by aghimpu**
Path to production:

- [ ] Review and make fixes on this branch
- [ ] Add email validation to this (and the old) signup flow: https://github.com/teamforus/development/issues/284#issuecomment-584832464
- [ ] Approve MVP to be deployed as signup/v2
- [ ] Maintain both signupflows in production
- [ ] Test with real endusers
- [ ] Make some iterations based on user feedback
- [ ] Depreciate old signup flow

Workflow:
- [ ] create a new branch from develop
- [ ] copy in css and js of this signupflow
- [ ] make available on /signup-v2 route

Make fixes

### CODE REVIEW

**Comment by dev-rminds** [comment]
Add "apply to funds" step and restore "Deze pagina is niet mobiel te benaderen." message when people open sign-up page from mobile phone.

**Comment by maxvisser** [comment]
Before this can be merged:
- [ ] both apps needs a way to better validate e-mailadres and login
- [ ] texts needs to be reviewed / translated https://github.com/teamforus/development/issues/183
- [ ] office step needs to be reviewed by @Myshelova as it does not work great UI/UX

**Comment by maxvisser** [comment]
image

I think these buttons need to be moved up a bit

**Comment by maxvisser** [comment]
Feedback:
- [x] google maps is not there
image
- [ ] no example opening times are displayed
image
- [x] employee should only be invited when submitting form (or add a popup after adding one are u sure you want to invite this employee? we will send a e-mail to this person inviting him for your organisation.)
image 
- [x] popup on fund apply page can be removed; should be the next page (aanvraag voltooid)
image
should be:
image

**Comment by maxvisser** [comment]
@aghimpu texts are updated in figma could you adjust it in frontend?

**Comment by maxvisser** [comment]
I think these issues also need to be fixed before merging:
https://github.com/teamforus/forus/issues/868
https://github.com/teamforus/me/issues/152

**Comment by aghimpu** [comment]
@maxvisser , I updated all the translations (and replaced some harcoded texts with actual translations)

**Comment by maxvisser** [comment]
alot weird css changes are on this branch. Buttons etc on dashboard are alot bigger

**Comment by jamalv** [comment]
Path to production discussed yesterday with @maxvisser and @GerbenBosschieter:

- [ ] Review and make fixes on this branch
- [ ] Approve MVP to be deployed as signup/v2
- [ ] Maintain both signupflows in production
- [ ] Test with real endusers
- [ ] Make some iterations based on user feedback
- [ ] Depreciate old signup flow

**Comment by jamalv** [comment]
Feedback:
- [ ] Steps on the bar have square edges, should be round
Screenshot 2020-01-29 at 08 01 49
Screenshot 2020-01-29 at 08 02 52

- [ ] Step 3: should use google api to autofill address
- [ ] Step 3: When check/unchecking openingtimes the display/hide behaviour should work both ways
- [ ] Step 3: Openingtimes should be visible (currently invisible)
- [ ] Employee confirmation message should be translated
- [ ] Test transaction does not work
image

**Comment by maxvisser** [comment]
@aghimpu do you understand the task here?
- [ ] create a new branch from develop
- [ ] copy in css and js of this signupflow
- [ ] make available on /signup-v2 route

after this you may start on fixing the things jamal found; please ask him to elaborate where it is not clear.

**Pull request closed without merging**
