### PR TITLE
Webshop map, add provider detail translations

### PR DESCRIPTION
**Pull request by aghimpu**

### CODE REVIEW

**Review by maxvisser — APPROVED** [review]

**Comment by maxvisser** [comment]
As you added count back please check if this is now the correct count; It should display the amount of organizations approved instead of offices on the map.

**Comment by aghimpu** [comment]
@maxvisser , do you mean the translation from i18n/nl/modals/modal-offices.js with the key "header.title"? I didn't add it anywhere, I just checked and it seems that it wasn't used anywhere.

**Comment by aghimpu** [comment]
@maxvisser , I see now. The pull request was based on this task https://github.com/teamforus/forus/issues/1090, just now I noticed https://github.com/teamforus/forus/issues/1089.

**Comment by maxvisser** [comment]
No problem. :)

**Pull request merged**
