### PR TITLE
Feature website footer

### PR DESCRIPTION
**Pull request by GerbenBosschieter**

### CODE REVIEW

**Comment by jamalv** [comment]
Sweet footer!

Feedback: 
- Would add some padding above the footer, suggestion is 80px;
- With the mobile menu (at least in safari) the states of the x / + are switched. When the menu is collapsed it shows an x and when it is expanded it shows a +
- We can hide the contact form on the contact page

**Comment by maxvisser** [comment]
Feedback:
remove headings: Sitemap, Contact, Contact
add hover on bold links in footer
remove 'producten' and 'succesverhalen' change Forus to Product
hall of fame seems to link to about us

I would maybe even suggest to remove the whole contact page after implementing this

**Comment by jamalv** [comment]
i don’t like the idea of removing the contact page, it should be super easy to reach us from anywhere, scrolling to the footer it’s too hidden

**Comment by GerbenBosschieter** [comment]
I will process most of the feedback that everybody agrees on, after the those changes we can review it again. @jamal what do you think of the other feedback that @maxvisser gave, except the thing about the contact page.

**Comment by jamalv** [comment]
- I would keep the headers (also from a screenreader and SEO perspective) but rename the last one to “Contactformulier” so that we loose the Contact, Contact, i think that’s mostly what makes it weird.
- Hover seems like a good idea
- Removing those items is kind of a quickfix for now, but re-introduces the problem that Zuidhorn is not a product. I would keep it like this. When we have more products and stories it will make more sense. I think it’s a good idea to make the product pages for Meedoen-regeling and kerstpakket already. issues: https://github.com/teamforus/forus/issues/903 and https://github.com/teamforus/forus/issues/933
- Nice catch on the broken link, max :)

**Comment by GerbenBosschieter** [comment]
The reference to the link is just fine, the problem is the way we display the hall of fame. It's get loaded onto the about us view and that's why it gets redirected to the about us page. Will try to fix this.

**Comment by maxvisser** [comment]
I have no strong opinion on the headings, my opinion is that the footer is pretty big for such a small website. I can agree with adding more pages solves this issue aswell (instead of removing headings now and adding them back later)

**Comment by GerbenBosschieter** [comment]
@maxvisser @jamalv 

What kind of hover do you guys want ?

**Comment by maxvisser** [comment]
Color change from dark text to light.

**Comment by GerbenBosschieter** [comment]
okay guys, what about now ?

**Comment by jamalv** [comment]
Looks all good!

**Review by jamalv — APPROVED** [review]

**Review by maxvisser — APPROVED** [review]

**Pull request merged**
