### PR TITLE
Release v0.14.0

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
- External validators pages:
	- shortlisted validators
	- funds you validate for
	- sponsor: funds list and edit improvements
- Bulk CSV upload improvements
- provider signupflow fund logo
- Fund criteria title

### CODE REVIEW

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Weird input field bug at provider signup flow.

Screenshot 2020-08-05 at 13 21 37

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Screen Shot 2020-08-12 at 14 30 37

Press one time one the number 1, get two times the number. 

Rejected

**Comment by maxvisser** [comment]
@GerbenBosschieter This was part of release v0.13.1 and is aswell on production. If you want we can fix this but I see no reason to block this release.

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Step indicator mobile is broken: (again or still)

IMG_0669

emailadres should be e-maiadres
IMG_4729B808C023-1

**Comment by maxvisser** [comment]
Did you check this on production? Nothing has changed here since v0.13.1

**Pull request merged**
