### PR TITLE
improvements for responsiveness text/image columns

### PR DESCRIPTION
**Pull request by GerbenBosschieter**

### CODE REVIEW

**Comment by maxvisser** [comment]
could you solve merge conflicts

**Review by maxvisser — CHANGES_REQUESTED** [review]
solve merge conflicts

**Comment by GerbenBosschieter** [comment]
No i can't. Could you do it ?

**Comment by GerbenBosschieter** [comment]
If i combine your fixes for the download buttons with my responsiveness fixes it the page is broken. Can't fix this. I am sorry.  I will just ac accept your incoming changes and the responsiveness issue will stay for now

**Pull request closed without merging**
