### PR TITLE
Replaced Me landing page with website

### PR DESCRIPTION
**Pull request by maxvisser**
lets add modal auth first before merging

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
- **Neem contact op** Button has wrong padding and doesn't work
- Navbar on mobile doesnt work

**Comment by maxvisser** [comment]
@jamalv you can run frontends locally and go to port 6500

**Comment by jamalv** [comment]
Looks awesome! Some remarks:
- it would be good to show a confirmation after a user fills their email and clicks send:
  - De email is verzonden. Open uw email en klik op de link om verder te gaan.
    - _preferably using the same modal popup but replacing the content_
- I was unable to login using the qr code (what environment should my me app connect to?)

After this is fixed I think we can merge and deploy this?

**Comment by maxvisser** [comment]
Depends on your the first line of your qdt-env.js (before gulp compile). Standard this is dev.api.forus.io; you will need the dev app to connect.

You can edit this row to test it on staging or demo aswell

**Review by jamalv — APPROVED** [review]

**Pull request merged**
