### PR TITLE
Provider dashboard, funds page improvements

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/forus/issues/1144

### CODE REVIEW

**Comment by maxvisser** [comment]
image

1. Change titles of specific tabs to 'Actieve fondsen', 'Uitnodigingen', 'Beschikbare fondsen', 'Archief'
2. Add counters to each tab to see how many there are without clicking. 
2. Move uitnodigingen to third place in tab selector (beschikbaar to second)
3. these statuses are now overkill, can be removed. 

4. If not hard to do maybe open tab 'beschikbaar' if no active funds

**Review by maxvisser — CHANGES_REQUESTED** [review]
image

1. Accepted status should be green
2. On an invite user does not need to see which right he is invited for

**Comment by maxvisser** [comment]
I am done with adjusting texts

**Comment by maxvisser** [comment]
Hi @aghimpu fixes are great; checked it out; Still need to review archive page
image
I would remove status on available funds as this has no purpose

**Comment by aghimpu** [comment]
> I would remove status on available funds as this has no purpose

Done

**Pull request merged**
