### PR TITLE
Sponsor dashboard, reject/hide application of provider

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/forus/issues/2296

### CODE REVIEW

**Comment by maxvisser** [comment]
image
Seems that you added a whole new row; You should only add the delete (bin) button

**Review by maxvisser — CHANGES_REQUESTED** [review]
remove extra row and move the bin button the existing row

**Comment by maxvisser** [comment]
@dev-rminds lets discuss this during next refinement whats still needed to merge

**Comment by lexlog** [comment]
refinement note - remove it due to not clear enough proposal

**Pull request closed without merging**
