### PR TITLE
Release/v0.22.0

### PR DESCRIPTION
**Pull request by maxvisser**

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 22 06 30

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 22 04 31

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 59 35

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 58 02

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-26 at 06 53 08

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 56 54

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 53 42

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 51 20222

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 48 04

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 29 27

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 39 19

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 57 54

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-03-25 at 21 34 30

**Comment by GerbenBosschieter** [comment]
@maxvisser The images above are all images that should be reviewed. Jij/jouw is missing and just some text review in general for these would be nice

**Comment by maxvisser** [comment]
fixed most of the issues; provider page and mail footer I left not fixed for now.

**Review by GerbenBosschieter — APPROVED** [review]
https://forus.testquality.com/project/11140/plan/19082/run/146428

**Pull request merged**
