### PR TITLE
Release v0.15.0

### PR DESCRIPTION
**Pull request by maxvisser**
- New Navigation 
- Mobile navigation
- Noordoostpolder fixes
- Actions
- Physical cards

### CODE REVIEW

**Comment by maxvisser** [comment]
Discussed with gerben to leave out Actions and Physical cards out of scope of this acceptance test. We will do this for next release v0.16.0 planned to be released on v0.16.0

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Looks like we have a bug with scanning in product vouchers. Tested different versions with the app, all have the same problem om backend 0.15.0

@maxvisser could you check this out on android
@dev-rminds @aghimpu could you check if you can find something in backend that causes this?

**Comment by maxvisser** [comment]
Same with Android :)

**Comment by maxvisser** [comment]
Me-debug aswell

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
