### PR TITLE
Header auth, add caret on webshop and dashboards

### PR DESCRIPTION
**Pull request by aghimpu**
https://github.com/teamforus/forus/issues/1190

### CODE REVIEW

**Review by dev-rminds — CHANGES_REQUESTED** [review]
Implement changes we discussed

**Comment by maxvisser** [comment]
please make the text elements and carret white on Nijmegen 
image

**Comment by maxvisser** [comment]
On mobile the carret can be hidden. I would also hide the me logo as it takes alot of space.
image

**Review by maxvisser — CHANGES_REQUESTED** [review]
- [ ] hide carret from mobile 
- [ ] overwrite css to make carret and texts white on nijmegen (like it was before)
image
suggestion: use always the color of the navbar text.

**Review by maxvisser — APPROVED** [review]

**Pull request merged**
