### PR TITLE
Add voucher transaction batch

### PR DESCRIPTION
**Pull request by ateamcms**

### CODE REVIEW

**Comment by lexlog** [comment]
checked qa, all is fine
    - [x] Scenarios
        - [x] Main positive
            - [x] 2 records on one voucher
            - [x] Different voucher
            - [x] <
            - [x] =
                - [x] 29s
                - [ ] check on staging for timeout of request
            - [x] >2500 records
                - [x] The file must contain no more than 2500 transactions but the selected file contains 5000 transactions.
        - [x] Main negative
            - [x] Sum more than voucher amount
            - [x] One raw amount more than voucher amount
            - [x] Sum of one voucher is > than voucher budget and other vouchers having  correct sum
            - [x] Voucher doesn’t exist
            - [x] Necessary fields forgotten
                - [x] Voucher id
                - [x] Amount
                - [x] Iban
                - [x] Iban name
                - [x] Two fields forgotten
                - [x] All fields forgotten
            - [x] IBAN incorrect
        - [x] Side negative
            - [x] Deactivated voucher
            - [x] Initially inactive voucher
            - [x] Expired voucher of expired fund
￼
            - [x] Long values
            - [x] - amount
            - [x] 0 amount
                - [x] 0.02 minimum
            - [ ] Character encoding

**Comment by lexlog** [comment]
for this PR left translations ( @GerbenBosschieter will check )

**Review by lexlog — APPROVED** [review]

**Comment by lexlog** [comment]
for this PR left translations ( @GerbenBosschieter will check )

**Comment by GerbenBosschieter** [comment]
@lexlog So I've added the translation but as I thought it's not correct now. But at least it has the dutch translation for the current text. For Release we could keep it like this. I don't consider the current situation a blocker.

Why it's not correct:

**Naam begunstigde** is literally the name you fill in during a bank payment. **IBAN TO** is currently being used for exactly the same. So this is double the information. (I checked this with different scenario's)
Screenshot 2023-01-30 at 14 31 14

So there are no two options we have:
1. Remove this whole line, because it will always be visible at "IBAN to"
2. Use this line for the target we use on a different place. So show the sponsor where this transaction was triggered from. Currently we have a couple of "Targets" (not sure if I will cover all of them)
    - IBAN
    - Aanbieder
 
We have this on voucher-details page. In the following directive: `voucher-transactions.pug`
 
Screenshot 2023-01-30 at 14 40 15

**Comment by GerbenBosschieter** [comment]
@lexlog added translations. But this one needs to be properly tested. Context for these one is important and I need to see it visually to be sure. Also not sure if I broke something with my changes

**Comment by lexlog** [comment]
> @lexlog added translations. But this one needs to be properly tested. Context for these one is important and I need to see it visually to be sure. Also not sure if I broke something with my changes

will notify when its on stage

**Pull request merged**
