### PR TITLE
Feature about us

### PR DESCRIPTION
**Pull request by maxvisser**
added history page

### CODE REVIEW

**Review by jamalv — CHANGES_REQUESTED** [review]
@maxvisser Nice work on the responsiveness! Just some minor styling fixes needed:

## Too far to the left:
Screenshot 2019-05-14 at 08 43 42

## A little too low:
Screenshot 2019-05-14 at 08 48 02

## Line goes to far up:
Screenshot 2019-05-14 at 08 50 54

And not sure, but the middle balls seem a bit too big to me

**Comment by maxvisser** [comment]
fixed these. (hopefully)

**Comment by jamalv** [comment]
Just this one left: 

Screenshot 2019-05-14 at 12 47 41

In zeplin:

Screenshot 2019-05-14 at 12 49 10

**Comment by maxvisser** [comment]
done

**Review by jamalv — APPROVED** [review]

**Pull request merged**
