### PR TITLE
fixed play btn

### PR DESCRIPTION
**Pull request by maxvisser**

### CODE REVIEW

**Comment by jamalv** [comment]
when running this locally:
$ npm install -g npm
$ cp qdt-env.sample.js qdt-env.js
$ node ./node_modules/gulp/bin/gulp.js

It doesn't work for me. 😕

**Comment by maxvisser** [comment]
What does console give as an error? (inspect element)

**Comment by maxvisser** [comment]
What does console give as an error? (inspect element)

**Comment by jamalv** [comment]
Ah wait, it works when I click the play button in the gif. 

If you click one of the play buttons below the video first, it doesn't work though (they _do_ work if you click them after first clicking the gif play button).

**Comment by maxvisser** [comment]
I deployed this branch already to forus.io yesterday evening (for testing my pipeline with different branches)

**Comment by maxvisser** [comment]
On chrome it works for me; you used safari?

**Comment by jamalv** [comment]
safari and chrome: https://drive.google.com/file/d/1vu10Ie5BUVJYF-T9F9ZR5GSm6_400Mjo/view?usp=sharing

**Comment by jamalv** [comment]
seems good now!

**Review by jamalv — APPROVED** [review]

**Pull request merged**
