### PR TITLE
Release/v0.27.0

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
- Generic search
- Requester signupflow overview page
- Move email login, fixes for NOP small screens
- Add option to cancel fund application for provider
- Financial dashboard overview, data division by zero fix
- WCAG Fixes: Skiplinks, Webshop providers map, remove list button, use button elements for to right buttons
- Webshop home page, add hover for products in the subsidy products block
- Webshop navbar: Move email login name, fixes for NOP search and small screens

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
Can't remove employee anymore

Screenshot 2021-06-23 at 10 34 42

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-06-23 at 12 04 41

**Comment by GerbenBosschieter** [comment]
Scenario: bsn and partner bsn uploaded with csv file. Should get an modal that partner already activated this fund, but modal doesnt open.

Screenshot 2021-06-23 at 13 31 20

Screenshot 2021-06-23 at 13 33 02

**Comment by GerbenBosschieter** [comment]
Export doesn't seem to work properly when I filter on "exported". Export also gives me the rows that where not exported yet. Not sure if this is currently on master.

@maxvisser could you check if this is currently also on master? this one is important. Activation codes are being send by letter based on the "Exported" status.

Screenshot 2021-06-24 at 10 11 56

**Comment by GerbenBosschieter** [comment]
URL filter provider sign up flow doesn't work properly. I do get the fund I filtered it on but still have the option to select an organisation or label while this doesn't make any sense cause you will not get any results of because of the filter itself.

Not sure if this is currently on master

Screenshot 2021-06-24 at 09 41 20

**Review by GerbenBosschieter — APPROVED** [review]
Test partially pass. Some test cases failed but where already a bug on production. To check all the scenario's that where used during testing please check the [TestReport](https://drive.google.com/file/d/1iIRc91rcDUm-7PBzPFl8LDfR1Q99HxP8/view?usp=sharing)

**Comment by maxvisser** [comment]
> Export doesn't seem to work properly when I filter on "exported". Export also gives me the rows that where not exported yet. Not sure if this is currently on master.
> 
> @maxvisser could you check if this is currently also on master? this one is important. Activation codes are being send by letter based on the "Exported" status.
> 
> Screenshot 2021-06-24 at 10 11 56

also issue on production; seem to be the case with all filters that it exports them all; (aswell search)

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
BUG:

Generic search doesn't filter on implementation. So it doesn't matter what webshop you are on, you will find ALL results of ALL implementations.

**Pull request merged**
