### PR TITLE
Feature fix backlog mobile

### PR DESCRIPTION
**Pull request by maxvisser**
added backlog carrossel on mobile with pagination for page forus.io/#!/nu (current.pug)

### CODE REVIEW

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Almost there.
Still need some small fixes. See images

- [ ] It looks like adding more cards wil not automatically adjust the height so it fits in the parent div.
- [ ] Are "nu bezig",  "backlog" and "Klaar" buttons ? If so, they do'nt work. these buttons are not always visible on different devices

IMG_0305

IMG_9308286DAC3A-1

**Comment by maxvisser** [comment]
@gerben which devices?

**Comment by maxvisser** [comment]
fixed made, column relative. buttons are absolute position on the bottom of container and column container has a margin bottom to show these buttons; this probably can be optimized but needs some more refactoring

**Comment by GerbenBosschieter** [comment]
Still see some parts where text is overflowing the parent div, but very rarely But it's good enough for now :)

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
