### PR TITLE
Feature.replace legacy phone control

### PR DESCRIPTION
**Pull request by lexlog**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## Developer suggestions
Checkmark if PR:
- [ ] *Needs Translations*
- [ ] *Could affect implementations custom css*
- [ ] *Need mobile design help/work*
- [ ] *Design include inconsistent*

## QA checklist
- [ ] Tag @ sashoa if design review needed
- [ ] *No regress in implementations custom css* - changes are not breaking other implementations designes
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- [ ] Translations are done

### CODE REVIEW

**Comment by lexlog** [comment]
problem with validation was not reproduced and as we though - it was git revert related 

but found another minor UI thin - phone number on provider sign up is not formatted according to chosen code (on second screen should be +31 123 456 789 instead of +3 112 345 678 9:

Screenshot 2023-10-30 at 10 23 22
Screenshot 2023-10-30 at 10 23 33

**Comment by ateamcms** [comment]
@lexlog added commit with UI fix

**Comment by lexlog** [comment]
@ateamcms can't approve because i created PR, but it's approved :) thanks! @dev-rminds assigned for code review

**Comment by lexlog** [comment]
feedback fixed, merging (can't approve own pr, but its recreated from Yaroslav and Valentin commits )

**Pull request merged**
