### PR TITLE
create provider notifications on product reservation cancel by client…

### PR DESCRIPTION
**Pull request by aghimpu**
…, add 'archive' tab for reservations on the webshop

### CODE REVIEW

**Comment by dev-rminds** [comment]
Made product name from the reservations table a link to the product details page and changed the date to match the style of dates from the other tables.
image

We still need to update the translation for the notification:
image

And also the translation on notifications list from the sponsor dashboard.
image

The are also couple other notifications in the sponsor dashboard notification types list that don't have translations/texts:
image

**Comment by lexlog** [comment]
qa:
- [ ] 1 cancelling "waiting" reservation
   - [ ] 1.1 goes to archive on webshop
   - [ ] 1.2 showed as cancelled on dashboard
   - [ ] 1.3 notification to provider came - see question 5
- [ ] 2. link for product in table

bugs:
- [ ] 2. its possible to cancel archived reservations, but when click it - redirected to active tab (without changing tab name) and without cancelling reservation itself
Screenshot 2023-01-11 at 7 25 27 PM
( on the screen you can see active tab after cancelling archived reservations list, but still archive tab active )
- [ ] 3. there are existed cancelled and outdated reservations in active
Screenshot 2023-01-11 at 7 29 53 PM

to clarify:
- [ ] 4. can't see new notifications on provider and sponsor dashboards ( branches are seems correct, because other functionality is visible)
- [ ] 5. shouldn't we have for provider cancelled at column also?

**Review by lexlog — CHANGES_REQUESTED** [review]
qa:
- [x] 1 cancelling "waiting" reservation
   - [x] 1.1 goes to archive on webshop
   - [x] 1.2 showed as cancelled on dashboard
   - [x] 1.3 notification to provider came
- [x] 2. link for product in table

bugs:
- [x] 2. @aghimpu @dev-rminds its possible to cancel archived reservations, but when click it - redirected to active tab (without changing tab name) and without cancelling reservation itself
Screenshot 2023-01-11 at 7 25 27 PM
( on the screen you can see active tab after cancelling archived reservations list, but still archive tab active )
update on 16.01 - fixed

- [x] 3. @aghimpu @dev-rminds there are existed cancelled and outdated reservations in active
Screenshot 2023-01-11 at 7 29 53 PM
   ( for debug - first reservation is shown as archived, second - as active )
   Screenshot 2023-01-11 at 7 53 51 PM
   update on 16.01 - fixed

to clarify:
- [x] 4. can't see new notifications on provider and sponsor dashboards ( branches are seems correct, because other functionality is visible) - updated - need to run update system notifications 
- [x] 5. translations
  - [x] 6.1 @dev-rminds @aghimpu could you provide translations file in code for system notif. translations
  - [x] 6.2 @lexlog translate with someone dutch speaking
     - [x] Geannuleerd door aanvrager - add door aanbieder to geannuleerd (only for webshop)
     - [x] states/product_reservations.complete

**Comment by dev-rminds** [comment]
@lexlog two things worth mentioning
- Because the canceled reservations now are still visible to the provider, it's pretty simple for someone to flood provider's list with canceled reservations. Implementing a throttle of some kind would be and archived tab on provider dashboard should help. 
- We should probably add auto tests to check that expired  and canceled by requester reservations actually go to "archived" tab.

**Comment by RobinMeles** [comment]
@lexlog As discussed in our DevOps meeting, there were still translations missing for me to check out. Two of them were not related to reservations, but made translations anyways. About system_notifications.notifications.notifications_products.reservation_canceled:
- system_notifications.notifications.notifications_products.reservation_canceled.title = Reservering geannuleerd door aanvrager
- system_notifications.notifications.notifications_products.reservation_canceled.description = Aanbieders ontvangen dit bericht wanneer hun reservering door de aanvrager is geannuleerd.

On system notification detail page for notification above:
- Reservation canceled by the client. = Reservering is geannuleerd door de aanvrager.
- The reservation for product [product_naam] is canceled by client. = De reservering van [product_naam] is geannuleerd door de aanvrager.
image

About translations that were missing, but were not related to reservations:
- system_notifications.notifications.notifications_fund_providers.state_accepted.title = Aanbieder aanvraag is goedgekeurd
- system_notifications.notifications.notifications_fund_providers.state_accepted.description = Aanbieders ontvangen dit bericht wanneer hun aanmelding voor een fonds is geaccepteerd door de sponsor
.
- system_notifications.notifications.notifications_fund_providers.state_rejected.title = Aanbieder aanvraag is geweigerd
- system_notifications.notifications.notifications_fund_providers.state_rejected.description = Aanbieders ontvangen dit bericht wanneer hun aanmelding voor een fonds is geweigerd door de sponsor

**Review by lexlog — APPROVED** [review]

**Comment by GerbenBosschieter** [comment]
@lexlog I think the transaltions for the notification in system notifications are in backend. Not sure. I recall me searching for it during review a while ago when we introduced this feature.

Added to the issues that need my attention

**Pull request merged**
