### PR TITLE
Feature kindpakket page

### PR DESCRIPTION
**Pull request by maxvisser**

### CODE REVIEW

**Comment by jamalv** [comment]
if we merge this to develop, will it be automatically deployed to dev.forus.io? 😇

**Comment by maxvisser** [comment]
Deploying to dev needs to be done manually

**Comment by jamalv** [comment]
Ah alright. And to staging? Asking because I'd like to send it around for review by the people who are in the business case zuidhorn before we go live.

**Review by jamalv — CHANGES_REQUESTED** [review]
Noticed a few things:
* When deploying locally the images don't load. 
* The menu arrow glitches when turning around after clicking
* I'd like the menu structure to be as follows:

Screenshot 2019-05-07 at 10 58 13

**Comment by maxvisser** [comment]
yes images are not added; as the wireframe or design does not contain the right images

**Comment by maxvisser** [comment]
I think you use safari; could you try chrome aswell?

**Comment by maxvisser** [comment]
what if we change product to 'Waarom Forus' (i dont like your proposal of hiding succesverhalen in a hover on product names)

Left column
Succesverhalen
gemeente Nijmegen
gemeente Zuidhorn

Right column
Producten
Kindpakket
Meedoen-regeling
Kerstpakket
Maatwerk

**Comment by maxvisser** [comment]
this can grow towards something paystack.com does

Succes stories
Demo 

Right column
Voor gemeenten
Voor goede doelen
Voor ondernemers 

etc

**Comment by maxvisser** [comment]
Let's do top level Kindpakket, sub level gemeente Zuidhorn. As those two will be finished in the mvp

**Comment by jamalv** [comment]
Allright, thx for the feedback; I agree, let's make the menu:

Screenshot 2019-05-07 at 17 12 01

<details><summary>Future plans (if you're interested)</summary>

When we expand the scope to include Nijmegen and Meedoen, I'd also like to add a more general homepage (the current one is focussed mostly on the platform). The current homepage will then be added as a page in the menu called "forus" that is all about the platform. 

The new homepage will offer an overview of all the content on the website.

The menu will look like:

Wireframes-Home-4

My current idea for the homepage is as follows (still needs design work):

Wireframes-Home-3
</details>

**Comment by maxvisser** [comment]
page still needs to be abit more responsive; gerben is redoing css for _explain (image right / image left blocks); I will wait for that.

**Comment by jamalv** [comment]
Please use this image for in the laptop:

Screenshot 2019-05-07 at 17 56 42

**Comment by jamalv** [comment]
Betreft de content achter de download buttons; daar zal ik achteraan gaan.

**Review by jamalv — APPROVED** [review]

**Pull request merged**
