### PR TITLE
Release/v0.31.0

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
- Product reservations - notes and names - Flevoboys
- Validator dashboard add lead times
- Fund FAQ feature
- Fund Collapsable items
- Fund sign up button configurations
- Removal of fund grid
- New webshop fund labels
- Styling enhancements fund page
- Provider signup page, adjust fund sizes.
- Add external fund type
- All dependencies updated to latest version
- markdown fullscreen button fix

to be expected, 
CSS fixes, fund description to funds list webshop
Fund details page on sponsor dashboard

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
Can't start a subsidy as a sponsor. Console network tabs give me the following error.


> message: "The POST method is not supported for this route. Supported methods: GET, HEAD, PUT, PATCH."

Screenshot 2021-12-23 at 15 40 25

**Comment by maxvisser** [comment]
funds are closed on end_date instead of end_date + 1; if not fixed all funds get closed on 31 december 00:01 instead of 1 January 00:01

fondsen moeten past  gesloten worden op de dag na de eind datum. (tot en met)

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Problem with sign up flow for providers. Can;t apply for fund. Get server error.

Used a URL filter: https://staging.forus.io/provider/sign-up?tag=sdoa


Screenshot 2021-12-24 at 14 13 34

**Comment by GerbenBosschieter** [comment]
> Problem with sign up flow for providers. Can;t apply for fund. Get server error.
> 
> Used a URL filter: https://staging.forus.io/provider/sign-up?tag=sdoa
> 
> Screenshot 2021-12-24 at 14 13 34

It doesn't matter If I do this by signup flow with or without URL filter. Also happends when I try to apply to a fund via the dashboard

**Review by GerbenBosschieter — COMMENTED** [review]
Two emails are not being send:

1. Email to provider when they get accepted for a fund by the sponsor
2. Email to provider when they get rejected for a fund by the sponsor

**Review by GerbenBosschieter — COMMENTED** [review]
It is currently not possible to accept or reject provider applications. That causes the other problems described in earlier comments

**Review by GerbenBosschieter — APPROVED** [review]
Pass: https://web.testquality.com/site/forus/project/12011/runs/154158

**Review by RobinMeles — APPROVED** [review]

**Pull request merged**
