### PR TITLE
add table column tooltips

### PR DESCRIPTION
**Pull request by aghimpu**
## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## Developer suggestions
Checkmark if PR:
- [ ] *Needs Translations*
- [ ] *Could affect implementations custom css*
- [ ] *Need mobile design help/work*
- [ ] *Design include inconsistent*

## QA checklist
- [ ] Tag @ sashoa if design review needed
- [ ] *No regress in implementations custom css* - changes are not breaking other implementations designes
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- [ ] Translations are done

### CODE REVIEW

**Comment by dev-rminds** [comment]
@aghimpu feedback shared

**Comment by lexlog** [comment]
feedback for PR
1) there is accidental scrolling issue - if you move cursor from top to down from down to top, it can scroll infobox with descriptions
video - https://drive.google.com/file/d/1ISkruZgF0iVrM1NghLxeosqT81epGx4_/view?usp=drive_link
2) minor feedback point from Maarten and Sashooa needs to be added
https://github.com/teamforus/DevOps/issues/659#issuecomment-1911989677

for later ( https://github.com/teamforus/DevOps/issues/659#issuecomment-1943650343 )
3) column "fonds" needs to be added (was added after this PR I think)

**Comment by aghimpu** [comment]
1. @lexlog it seems to happen only when you move your cursor over the column header and it was done because the list is pretty long and the user might miss the description of the active column.
Do you think we should just remove this feature completely?

**Comment by dev-rminds** [comment]
@lexlog @aghimpu one option would be to add a small delay, 200ms maybe?

**Comment by lexlog** [comment]
@aghimpu @dev-rminds 

> Do you think we should just remove this feature completely?

> one option would be to add a small delay, 200ms maybe?

200ms sounds good as a solution

**Review by lexlog — APPROVED** [review]

**Pull request merged**
