### PR TITLE
Epic - custom notifications

### PR DESCRIPTION
**Pull request by dev-rminds**

### CODE REVIEW

**Comment by maxvisser** [comment]
image
signature does not take into account new lines

**Comment by maxvisser** [comment]
Images and QR-code don't load in gmail?

image

image

**Comment by dev-rminds** [comment]
@maxvisser 
fixed: https://github.com/teamforus/forus-backend/pull/1274

**Comment by maxvisser** [comment]
Nice! Tested it and the images / qr-codes now work:
image

Only the images are a really low quality (pixelated)

**Comment by maxvisser** [comment]
In some places variables replacement is broken as the first part of the variable is the same as different variable.

image

image

**Comment by maxvisser** [comment]
image
Small problem with the variable buttons where the text for email_signature and email_logo don't load

**Comment by maxvisser** [comment]
image
:header_icon in employee invite mail is missing

**Comment by maxvisser** [comment]
Test list
1. notifications_identities.added_employee
- [x] No issues found -> header_icon in e-mail not being sent, database notifications not being sent
2. notifications_identities.changed_employee_roles
- [x] No issues found -> database notifications not being sent
3. notifications_identities.removed_employee 
- [x] No issues found -> database notifications not being sent
4. notifications_fund_providers.approved_budget 
- [x] No issues found
5. notifications_fund_providers.approved_products
- [x] No issues found
6. notifications_fund_providers.revoked_budget 
- [x] No issues found
7. notifications_fund_providers.revoked_products
- [x] No issues found 
8. notifications_fund_providers.sponsor_message
- [x] No issues found -> needs text review
9. notifications_identities.requester_provider_approved_budget
- [x] No issues found -> cant test webshop notifications don't work
10. notifications_identities.requester_provider_approved_products
- [x] No issues found -> cant test webshop notifications don't work


Default template remarks:
notifications_fund_providers.approved_budget  is missing the button to go to the dashboard
notifications_fund_providers.approved_products has a typo
notifications_fund_providers.revoked_budget weird interaction, mail text does not takes into account rejection after approval
 notifications_identities.requester_provider_approved_products is the same as notifications_identities.requester_provider_approved_budget (For the citizen this feels like a duplicate)

**Comment by maxvisser** [comment]
@dev-rminds could you check why webshop notifications don't work? I am not getting any errors in console / laravel.log

**Comment by pathwaynavigator** [comment]
image

Needs a "Voorbeeld" hover text just like the other buttons in the row. When I go over it does not say.

**Pull request merged**
