### PR TITLE
Release 0.0.3b

### PR DESCRIPTION
**Pull request by GerbenBosschieter**
translation bugfixes

### CODE REVIEW

**Comment by jamalv** [comment]
This pull request is redundant, the commit was automatically added to: https://github.com/teamforus/forus-frontend/pull/33

Can be closed.

**Comment by jamalv** [comment]
Oh wait, too soon 😅 that one is into master, this one into staging :)

**Comment by GerbenBosschieter** [comment]
I missed a translation variable fix. Lets keep it open for now, maybe more fixes will arise.

**Review by maxvisser — APPROVED** [review]

**Review by jamalv — APPROVED** [review]

**Comment by maxvisser** [comment]
lets wait a bit and finish all translation before releasing a bug fix

**Pull request closed without merging**
