### PR TITLE
Add custom reservation fields

### PR DESCRIPTION
**Pull request by ateamcms**
## Changes description
- [ ] Updated modals on webshop (added scroll bar)

## Developer suggestions
Checkmark if PR:
- [ ] *Needs Translations*
- [ ] *Could affect implementations custom css*

## QA checklist
- [ ] Feature is tested in different screen sizes - desktop, mobile
- [ ] Translations are done

### CODE REVIEW

**Comment by lexlog** [comment]
@aghimpu you can take branch from this PR to proceed with redesign

**Review by lexlog — CHANGES_REQUESTED** [review]
Robin has a question to Valentin about PR
plan for PR to include in tomorrows release

**Comment by RobinMeles** [comment]
@dev-rminds Since Yaroslav is on holiday, could you maybe help me with this question? I noticed the same block markdown is used in custom reservation fields ([here](https://github.com/teamforus/forus-frontend/blob/a6a4f815848013f261d8c652ea5dd2397dcee1d9/src/sources/forus-platform/pug/tpl/directives/reservation-fields-editor.pug#L89)), as what we used in the BI connection feature ([here](https://github.com/teamforus/forus-frontend/blob/76b853de8bda6eae66092139bb6537d66f24345e/src/sources/forus-platform/pug/tpl/pages/bi-connection.pug#L38)).

image

Above info block is in the context of making a new reservation field, not really needed. Is this info block intended? If so, could I change translations or does this directly impact the info block for the BI connection aswel? And else, could this block be exluded?

**Comment by RobinMeles** [comment]
> @dev-rminds Since Yaroslav is on holiday, could you maybe help me with this question? I noticed the same block markdown is used in custom reservation fields ([here](https://github.com/teamforus/forus-frontend/blob/a6a4f815848013f261d8c652ea5dd2397dcee1d9/src/sources/forus-platform/pug/tpl/directives/reservation-fields-editor.pug#L89)), as what we used in the BI connection feature ([here](https://github.com/teamforus/forus-frontend/blob/76b853de8bda6eae66092139bb6537d66f24345e/src/sources/forus-platform/pug/tpl/pages/bi-connection.pug#L38)).
> 
> image
> 
> Above info block is in the context of making a new reservation field, not really needed. Is this info block intended? If so, could I change translations or does this directly impact the info block for the BI connection aswel? And else, could this block be exluded?

Valentin explained the use of this info block and informed me that this specific text could be changed. I will proceed with translations and add a more descriptive text

**Review by RobinMeles — APPROVED** [review]

**Pull request merged**
