### PR TITLE
Feature white dashboard

### PR DESCRIPTION
**Pull request by maxvisser**

### CODE REVIEW

**Comment by jamalv** [comment]
image

**Comment by jamalv** [comment]
dependancy: we'd like to do a pizza party to match figma with this PR

**Comment by jamalv** [comment]
@GerbenBosschieter what's your perspective on this PR from an acceptance standpoint? Could it be merged?

**Comment by GerbenBosschieter** [comment]
Due the fact that this PR is open for a while, will not go anywhere and way to much merge conflicts I decided to close this PR. 

IMG_2272

**Pull request closed without merging**
